
# Disable to allow for faster indexing of fewer data (useful for development)
download_full = true

[twitch]
# https://api-docs.igdb.com/#account-creation
client_id = "your_client_id"
client_secret = "your_client_secret"
